name: Development Node server build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Upload to ECR and tag
        uses: alphagov/di-devplatform-upload-action-ecr@1.0.1
        with:
          role-to-assume-arn: ${{ secrets.DEV_ROLE_TO_ASSUME }}
          container-sign-kms-key-arn: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
          ecr-repo-name: ${{ secrets.DEV_ECR_REPOSITORY }}
          artifact-bucket-name: ${{ secrets.DEV_ARTIFACT_BUCKET }}