name: Pre-merge checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  push:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Checks if commiting secrets to repo
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: "detect-secrets --all-files"

      - name: Install dependencies
        run: yarn install
        
      - name: Run lint
        run: yarn lint

      - name: Run build
        run: yarn build
        
      - name: Run test and write coverage
        run: yarn test:coverage

      - name: Run browser tests
        run: npm run test:browser:ci
        env: 
          IPV_STUB_URL: ${{ secrets.IPV_STUB_URL }}
          CUSTOM_FE_URL: http:/localhost:5020 
          LANGUAGE_TOGGLE_DISABLED: false

      - name: Archive browser tests results
        uses: actions/upload-artifact@v4
        with:
          name: cic-code-coverage-report
          path: test/reports/cic-reports/

  sonar-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install dependencies
        run: yarn install
        
      - name: Run lint
        run: yarn lint
      
      - name: Run build
        run: yarn build
      
      - name: "Run SonarCloud Scan"
        if: ${{ success() && github.actor != 'dependabot[bot]' }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}