name: Pull Request CI - Sonar
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'yarn'
      - name: Build Test CIC Front Image
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run lint
        run: yarn lint
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test:browser:ci # will run `yarn test` command
        env:
          IPV_STUB_URL: ${{ secrets.IPV_STUB_URL }}
      - name: "Run SonarCloud Scan"
        if: ${{ success() }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
